#!/usr/bin/env python3
"""Generate the priority-ranked board from initiative frontmatter -- the single source
(KNOWLEDGE.md's 2026-07-14 "Assignments" rule). Priority is a dense rank the user states
explicitly (never inferred); unset priority falls back to a config-driven default by kind
and cycle. See docs/state-board.md in the wiki (or the wiki's own analyses/ page) for the
rule this implements; nothing about the rule itself is hardcoded here, only the mechanics.

Usage:
  board.py [WIKI_ROOT]                  print the board to stdout
  board.py [WIKI_ROOT] --write          replace the block between <!-- board:begin -->
                                         and <!-- board:end --> in STATE.md
  board.py [WIKI_ROOT] --repo NAME      also print one "Actionable now for NAME" line,
                                         the first Now/Next row not waiting on anyone whose
                                         repos (if set) contains NAME or carries no repos
"""
import argparse
import datetime
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wikilib

BEGIN = "<!-- board:begin (generated by hooks/board.py from initiative frontmatter; do not edit) -->"
END = "<!-- board:end -->"
KIND_ORDER = {"pitch": 0, "assigned": 1, "self": 2}
MAX_ROWS = 12
STALE_RANK_DAYS = 30


def wc(s):
    return len(s.split()) if s else 0


def load_initiatives(kb):
    out = []
    for f in wikilib.git_files(kb):
        if not f.startswith("initiatives/") or os.path.basename(f) == "index.md":
            continue
        text = wikilib.read(kb, f)
        fmblock = re.match(r"^---\n(.*?)\n---", text, re.S)
        if not fmblock:
            continue
        fm = fmblock.group(1)
        if wikilib.frontmatter_value(fm, "type") != "initiative":
            continue
        if wikilib.frontmatter_value(fm, "board") == "false":
            continue
        out.append({
            "path": f,
            "slug": os.path.splitext(os.path.basename(f))[0],
            "title": wikilib.frontmatter_value(fm, "title") or f,
            "kind": wikilib.frontmatter_value(fm, "assignment_kind") or "",
            "status": wikilib.frontmatter_value(fm, "assignment_status") or "",
            "priority": wikilib.frontmatter_value(fm, "priority"),
            "priority_set": wikilib.frontmatter_value(fm, "priority_set"),
            "cycle": wikilib.frontmatter_value(fm, "cycle"),
            "next": wikilib.frontmatter_value(fm, "next") or "",
            "waiting_on": wikilib.frontmatter_value(fm, "waiting_on") or "none",
            "ask": wikilib.frontmatter_value(fm, "ask") or "",
            "repos": wikilib.fm_list(fm, "repos"),
            "timestamp": wikilib.frontmatter_value(fm, "timestamp") or "",
        })
    return out


def default_rank(item, current_cycle):
    if item["status"] == "parked":
        return 9
    if item["kind"] == "pitch":
        if current_cycle and item["cycle"] == str(current_cycle):
            return 1
        return 2
    if item["kind"] == "assigned":
        return 2
    return 3


def rank_of(item, current_cycle):
    p = item["priority"]
    if p and p.lstrip("-").isdigit():
        return int(p)
    return default_rank(item, current_cycle)


def stale_rank(item, today):
    ps = item["priority_set"]
    if not ps:
        return False
    try:
        age = (today - datetime.date.fromisoformat(ps)).days
    except ValueError:
        return False
    return age > STALE_RANK_DAYS


def sort_key(item):
    return (
        item["rank"],
        item["waiting_on"] != "none",
        KIND_ORDER.get(item["kind"], 3),
        item["timestamp"],
    )


def fmt_row(item, today):
    tag = "·".join(x for x in (item["kind"], item["status"],
                                f"c{item['cycle']}" if item["cycle"] else "") if x)
    line = f"{item['rank']}. [{tag}] {item['title']} → next: {item['next']}"
    if item["repos"]:
        line += f" (repos: {', '.join(item['repos'])})"
    if item["waiting_on"] != "none":
        line += f" [waiting on {item['waiting_on']}: {item['ask']}]"
    if stale_rank(item, today):
        line += f" → stale, set {item['priority_set']}"
    return line


def build(kb, repo=None):
    cfg = wikilib.load_config(kb)
    current_cycle = cfg.get("current_cycle")
    cycle_ends = cfg.get("cycle_ends")
    today = datetime.date.today()

    items = load_initiatives(kb)
    shipped, active = [], []
    for it in items:
        if it["status"] == "done":
            shipped.append(it)
            continue
        it["rank"] = rank_of(it, current_cycle)
        active.append(it)
    active.sort(key=sort_key)

    now_rows = [i for i in active if i["rank"] <= 2]
    next_rows = [i for i in active if 3 <= i["rank"] <= 5]
    later_rows = [i for i in active if i["rank"] >= 6]

    lines = [BEGIN]
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    hdr = f"## Board (generated {ts}"
    if current_cycle:
        hdr += f" · cycle {current_cycle}"
        if cycle_ends:
            try:
                ended = datetime.date.fromisoformat(cycle_ends) < today
            except ValueError:
                ended = False
            hdr += f" ends {cycle_ends}" + (" -- PASSED, re-set cycle_ends" if ended else "")
    hdr += " · priority is a rank you state, 1-9)"
    lines.append(hdr)

    waiting_andrew = [i for i in active if i["waiting_on"] == "andrew"]
    oa_text = wikilib.read(kb, "open-asks/andrew.md")
    oa_items = re.findall(r"(?m)^- (.+)$", oa_text)
    queue_total = len(waiting_andrew) + len(oa_items)
    lines.append(f"Waiting on Andrew ({queue_total}):")
    for i in waiting_andrew:
        lines.append(f"- {i['slug']} · {i['ask']}")
    for line in oa_items:
        lines.append(f"- (open-asks/andrew) {line}")

    shown = 0
    lines.append("Now:")
    for i in now_rows:
        if shown >= MAX_ROWS:
            break
        lines.append(fmt_row(i, today))
        shown += 1
    lines.append("Next:")
    for i in next_rows:
        if shown >= MAX_ROWS:
            break
        lines.append(fmt_row(i, today))
        shown += 1
    remaining = len(now_rows) + len(next_rows) - shown
    if remaining > 0:
        lines.append(f"+{remaining} more")

    lines.append("Later / parked: " + (" · ".join(i["slug"] for i in later_rows) or "none"))
    recent_shipped = sorted(
        (i for i in shipped if i["timestamp"]),
        key=lambda i: i["timestamp"], reverse=True,
    )[:5]
    lines.append("Shipped: " + (" · ".join(i["slug"] for i in recent_shipped) or "none"))
    lines.append(END)
    board = "\n".join(lines)

    pointer = None
    if repo:
        candidates = now_rows + next_rows
        for i in candidates:
            if i["waiting_on"] != "none":
                continue
            if i["repos"] and repo not in i["repos"]:
                continue
            pointer = f"Actionable now for {repo}: #{i['rank']} {i['title']} → {i['next']}"
            break
    return board, pointer


def write_state(kb, board):
    path = os.path.join(kb, "STATE.md")
    text = wikilib.read(kb, "STATE.md")
    if not text:
        return False
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        print(f"board.py: no {BEGIN} .. {END} markers in STATE.md; nothing written", file=sys.stderr)
        return False
    new_text = pattern.sub(lambda _: board.replace("\\", "\\\\"), text, count=1)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new_text)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root", nargs="?", default=None)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--repo", default=None)
    args = ap.parse_args()
    kb = wikilib.resolve_root(args.root)
    board, pointer = build(kb, repo=args.repo)
    if args.write:
        write_state(kb, board)
    else:
        print(board)
    if pointer:
        print(pointer)


if __name__ == "__main__":
    main()
